"""Derived strategy backtest for Gold rules.

This is explicitly not a reverse-engineering fidelity test. It reads synthetic
trades already generated by the frozen-rule replicator and asks a narrower
question: would the extracted rule logic have positive standalone economics
under simple XAUUSD round-trip cost overlays?

Citations (Regra 2): costs and turnover can dominate short-horizon systems
`[systematic_trading, p.182-197]`; bootstrap/DSR style inference is used
to avoid over-reading mined rules `[advances_fin_ml, p.196-211]`.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import norm

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from studies.myfxbook_reverse_engineering.shared.replicator import load_frozen_rule  # noqa: E402


TRADING_DAYS_PER_YEAR = 252
BOOTSTRAP_SEED = 7
BOOTSTRAP_N = 5_000
BOOTSTRAP_CI = 0.999
RANDOM_SUBSAMPLE_N = 500

GOLD_SYSTEMS = [
    "10281851",
    "11207608",
    "11355455",
    "2421356",
    "6541963",
    "8647517",
    # XAUUSD-only but not H1_MOMENTUM_GOLD; included as Gold-adjacent control.
    "9375654",
]

COST_SCENARIOS = {
    "gross_0p": 0.0,
    # XAUUSD 0.18-0.45 USD/oz spread ~= 18-45 pips when pip_size=0.01.
    "xau_conservative_45p": 45.0,
    "xau_stress_80p": 80.0,
}


@dataclass
class BacktestStats:
    system_id: str
    output_dir_name: str
    family: str
    cost_scenario: str
    cost_pips_rt: float
    fidelity_score: float | None
    score_band: str | None
    n_trades: int
    start: str
    end: str
    trades_per_year: float
    total_net_pips: float
    avg_net_pips: float
    median_net_pips: float
    win_rate: float
    profit_factor: float
    max_drawdown_pips: float
    daily_sharpe: float
    dsr_p: float
    boot_lo: float
    boot_hi: float
    wf_positive: int
    wf_total: int
    oos_start: str
    oos_sharpe: float
    oos_total_net_pips: float
    oos_boot_lo: float
    pass_basic_positive: bool
    pass_full_bootstrap: bool
    pass_oos_bootstrap: bool


@dataclass
class Tier2Stats:
    system_id: str
    output_dir_name: str
    family: str
    selection_mode: str
    cost_scenario: str
    cost_pips_rt: float
    n_real_trades: int
    n_synthetic_original: int
    n_selected: int
    total_net_pips: float
    avg_net_pips: float
    win_rate: float
    profit_factor: float
    daily_sharpe: float
    boot_lo: float
    oos_sharpe: float
    oos_boot_lo: float
    wf_positive: int
    wf_total: int
    random_sharpe_p95: float | None = None
    random_boot_lo_p95: float | None = None
    random_total_pips_p95: float | None = None


def _annualized_sharpe(daily: pd.Series) -> float:
    daily = daily.dropna()
    if len(daily) < 2 or daily.std() == 0:
        return 0.0
    return float(daily.mean() / daily.std() * math.sqrt(TRADING_DAYS_PER_YEAR))


def _bootstrap_sharpe(daily: pd.Series) -> tuple[float, float]:
    arr = daily.dropna().to_numpy(dtype=float)
    if len(arr) < 30:
        return float("nan"), float("nan")
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    sharpes = np.empty(BOOTSTRAP_N)
    for i in range(BOOTSTRAP_N):
        sample = rng.choice(arr, size=len(arr), replace=True)
        std = sample.std()
        sharpes[i] = sample.mean() / std * math.sqrt(TRADING_DAYS_PER_YEAR) if std > 0 else 0.0
    q = (1 - BOOTSTRAP_CI) / 2
    return float(np.quantile(sharpes, q)), float(np.quantile(sharpes, 1 - q))


def _dsr_p(sharpe: float, daily: pd.Series) -> float:
    d = daily.dropna()
    if len(d) < 30:
        return 1.0
    skew = float(d.skew())
    kurt_excess = float(d.kurt())  # pandas returns Fisher (excess) kurtosis
    # Bailey/López de Prado DSR variance: Var(SR) ≈ [1 - γ3·SR + (γ4_raw-1)/4·SR²] / (T-1).
    # γ4_raw = γ4_excess + 3, so (γ4_raw - 1)/4 = (γ4_excess + 2)/4.
    se_term = 1 - skew * sharpe + (kurt_excess + 2) / 4 * sharpe**2
    if se_term <= 0:
        return 1.0 if sharpe <= 0 else 0.0
    se = math.sqrt(se_term / (len(d) - 1))
    z = sharpe / se if se > 0 else 0.0
    return float(1 - norm.cdf(z))


def _profit_factor(net_pips: pd.Series) -> float:
    gains = float(net_pips[net_pips > 0].sum())
    losses = float(-net_pips[net_pips < 0].sum())
    if losses == 0:
        return float("inf") if gains > 0 else 0.0
    return gains / losses


def _max_drawdown(cum: pd.Series) -> float:
    if cum.empty:
        return 0.0
    dd = cum.cummax() - cum
    return float(dd.max())


def _score_meta(base: Path, sid: str, output_dir_name: str) -> tuple[float | None, str | None]:
    p = base / "systems" / sid / output_dir_name / "decoding_score.json"
    if not p.exists():
        return None, None
    data = json.loads(p.read_text())
    return data.get("fidelity_score"), data.get("score_band")


def _real_trade_count(base: Path, sid: str) -> int:
    p = base / "data" / "trades" / sid / "trades.parquet"
    df = pd.read_parquet(p)
    if "is_trade" in df.columns:
        df = df[df["is_trade"]]
    else:
        df = df[df["symbol"].astype(str).str.len() > 0]
    if "symbol" in df.columns:
        df = df[df["symbol"] == "XAUUSD"]
    return int(len(df))


def _prepare_xau_trades(df: pd.DataFrame, sid: str, cost_pips: float) -> pd.DataFrame:
    trades = df[df["is_trade"]].copy().sort_values("close_dt_utc")
    if trades.empty:
        return trades
    # Cost is XAUUSD pips (pip_size=0.01). Subtracting from non-XAU pairs would
    # mix units. GOLD_SYSTEMS is curated to be XAU-only; assert protects against
    # silent extension to mixed-pair systems.
    if not (trades["symbol"] == "XAUUSD").all():
        symbols_seen = sorted(trades["symbol"].unique().tolist())
        raise ValueError(
            f"derived_gold_backtest expects XAUUSD-only trades for {sid}; "
            f"got {symbols_seen}. Cost in XAU pips would be unit-inconsistent."
        )
    trades["net_pips"] = trades["pips"].astype(float) - cost_pips
    trades["close_date"] = trades["close_dt_utc"].dt.date
    return trades


def _summary_metrics(trades: pd.DataFrame) -> dict[str, Any]:
    if trades.empty:
        return {
            "total_net_pips": 0.0,
            "avg_net_pips": 0.0,
            "median_net_pips": 0.0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "max_drawdown_pips": 0.0,
            "daily_sharpe": 0.0,
            "dsr_p": 1.0,
            "boot_lo": float("nan"),
            "boot_hi": float("nan"),
            "wf_positive": 0,
            "wf_total": 0,
            "oos_start": "NA",
            "oos_sharpe": 0.0,
            "oos_total_net_pips": 0.0,
            "oos_boot_lo": float("nan"),
        }
    daily = trades.groupby("close_date")["net_pips"].sum().sort_index()
    sharpe = _annualized_sharpe(daily)
    boot_lo, boot_hi = _bootstrap_sharpe(daily)
    daily_ts = daily.copy()
    daily_ts.index = pd.to_datetime(daily_ts.index)
    splits = np.array_split(daily_ts.index, 8)
    wf_sharpes = []
    for idxs in splits:
        if len(idxs) < 5:
            continue
        wf_sharpes.append(_annualized_sharpe(daily_ts.loc[idxs.min():idxs.max()]))
    oos_cut_idx = int(len(daily_ts) * 0.8)
    oos_daily = daily_ts.iloc[oos_cut_idx:] if len(daily_ts) else daily_ts
    oos_lo, _oos_hi = _bootstrap_sharpe(oos_daily)
    net = trades["net_pips"]
    return {
        "total_net_pips": float(net.sum()),
        "avg_net_pips": float(net.mean()),
        "median_net_pips": float(net.median()),
        "win_rate": float((net > 0).mean()),
        "profit_factor": float(_profit_factor(net)),
        "max_drawdown_pips": _max_drawdown(net.cumsum()),
        "daily_sharpe": sharpe,
        "dsr_p": _dsr_p(sharpe, daily),
        "boot_lo": boot_lo,
        "boot_hi": boot_hi,
        "wf_positive": int(sum(1 for s in wf_sharpes if s > 0)),
        "wf_total": len(wf_sharpes),
        "oos_start": str(oos_daily.index.min().date()) if len(oos_daily) else "NA",
        "oos_sharpe": _annualized_sharpe(oos_daily),
        "oos_total_net_pips": float(oos_daily.sum()) if len(oos_daily) else 0.0,
        "oos_boot_lo": oos_lo,
    }


def compute_stats(base: Path, sid: str, output_dir_name: str, scenario: str, cost_pips: float) -> BacktestStats | None:
    synth_path = base / "systems" / sid / output_dir_name / "synthetic_trades.parquet"
    if not synth_path.exists():
        return None
    df = pd.read_parquet(synth_path)
    if df.empty:
        return None
    trades = _prepare_xau_trades(df, sid, cost_pips)
    if trades.empty:
        return None

    start_ts = pd.Timestamp(trades["open_dt_utc"].min())
    end_ts = pd.Timestamp(trades["close_dt_utc"].max())
    years = max((end_ts - start_ts).days / 365.25, 1 / 365.25)
    m = _summary_metrics(trades)

    fidelity, band = _score_meta(base, sid, output_dir_name)
    rule = load_frozen_rule(sid, base)
    return BacktestStats(
        system_id=sid,
        output_dir_name=output_dir_name,
        family=rule.family,
        cost_scenario=scenario,
        cost_pips_rt=cost_pips,
        fidelity_score=fidelity,
        score_band=band,
        n_trades=int(len(trades)),
        start=str(start_ts.date()),
        end=str(end_ts.date()),
        trades_per_year=float(len(trades) / years),
        total_net_pips=m["total_net_pips"],
        avg_net_pips=m["avg_net_pips"],
        median_net_pips=m["median_net_pips"],
        win_rate=m["win_rate"],
        profit_factor=m["profit_factor"],
        max_drawdown_pips=m["max_drawdown_pips"],
        daily_sharpe=m["daily_sharpe"],
        dsr_p=m["dsr_p"],
        boot_lo=m["boot_lo"],
        boot_hi=m["boot_hi"],
        wf_positive=m["wf_positive"],
        wf_total=m["wf_total"],
        oos_start=m["oos_start"],
        oos_sharpe=m["oos_sharpe"],
        oos_total_net_pips=m["oos_total_net_pips"],
        oos_boot_lo=m["oos_boot_lo"],
        pass_basic_positive=bool(m["total_net_pips"] > 0 and m["daily_sharpe"] > 0 and m["wf_positive"] >= 6),
        pass_full_bootstrap=bool(not math.isnan(m["boot_lo"]) and m["boot_lo"] > 0),
        pass_oos_bootstrap=bool(not math.isnan(m["oos_boot_lo"]) and m["oos_boot_lo"] > 0),
    )


def _uniform_k(trades: pd.DataFrame, k: int) -> pd.DataFrame:
    """Select k trades evenly over time. No PnL/feature lookahead is used."""
    if len(trades) <= k:
        return trades.copy()
    idx = np.linspace(0, len(trades) - 1, k, dtype=int)
    return trades.iloc[idx].copy()


def _oracle_best_k(trades: pd.DataFrame, k: int) -> pd.DataFrame:
    """Non-tradeable upper bound: choose best realized net_pips trades ex-post."""
    if len(trades) <= k:
        return trades.copy()
    return trades.sort_values("net_pips", ascending=False).head(k).sort_values("close_dt_utc").copy()


def _random_subsample_summary(trades: pd.DataFrame, k: int) -> tuple[float, float, float]:
    if len(trades) <= k:
        m = _summary_metrics(trades)
        return m["daily_sharpe"], m["boot_lo"], m["total_net_pips"]
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    sharpes: list[float] = []
    totals: list[float] = []
    for _ in range(RANDOM_SUBSAMPLE_N):
        sample_idx = rng.choice(len(trades), size=k, replace=False)
        sample = trades.iloc[np.sort(sample_idx)].copy()
        daily = sample.groupby("close_date")["net_pips"].sum().sort_index()
        sharpes.append(_annualized_sharpe(daily))
        totals.append(float(sample["net_pips"].sum()))
    return (
        float(np.nanquantile(sharpes, 0.95)),
        float("nan"),
        float(np.nanquantile(totals, 0.95)),
    )


def compute_tier2_stats(base: Path, sid: str, output_dir_name: str, scenario: str, cost_pips: float) -> list[Tier2Stats]:
    synth_path = base / "systems" / sid / output_dir_name / "synthetic_trades.parquet"
    if not synth_path.exists():
        return []
    raw = pd.read_parquet(synth_path)
    trades = _prepare_xau_trades(raw, sid, cost_pips)
    if trades.empty:
        return []
    k = min(_real_trade_count(base, sid), len(trades))
    if k <= 0:
        return []
    rule = load_frozen_rule(sid, base)
    rand_sharpe_p95, rand_boot_p95, rand_total_p95 = _random_subsample_summary(trades, k)
    out: list[Tier2Stats] = []
    selections = {
        "uniform_time_k_n_real": _uniform_k(trades, k),
        "oracle_best_net_pips_k_n_real_nontradeable": _oracle_best_k(trades, k),
    }
    for mode, selected in selections.items():
        m = _summary_metrics(selected)
        out.append(Tier2Stats(
            system_id=sid,
            output_dir_name=output_dir_name,
            family=rule.family,
            selection_mode=mode,
            cost_scenario=scenario,
            cost_pips_rt=cost_pips,
            n_real_trades=k,
            n_synthetic_original=int(len(trades)),
            n_selected=int(len(selected)),
            total_net_pips=m["total_net_pips"],
            avg_net_pips=m["avg_net_pips"],
            win_rate=m["win_rate"],
            profit_factor=m["profit_factor"],
            daily_sharpe=m["daily_sharpe"],
            boot_lo=m["boot_lo"],
            oos_sharpe=m["oos_sharpe"],
            oos_boot_lo=m["oos_boot_lo"],
            wf_positive=m["wf_positive"],
            wf_total=m["wf_total"],
            random_sharpe_p95=rand_sharpe_p95,
            random_boot_lo_p95=rand_boot_p95,
            random_total_pips_p95=rand_total_p95,
        ))
    return out


def _fmt(x: Any, digits: int = 3) -> str:
    if x is None:
        return "NA"
    if isinstance(x, float):
        if math.isnan(x):
            return "NaN"
        if math.isinf(x):
            return "inf"
        return f"{x:.{digits}f}"
    return str(x)


def write_report(
    base: Path,
    rows: list[BacktestStats],
    tier2_rows: list[Tier2Stats],
    out_md: Path,
    out_json: Path,
    out_tier2_json: Path,
) -> None:
    out_json.write_text(json.dumps([asdict(r) for r in rows], indent=2, default=str))
    out_tier2_json.write_text(json.dumps([asdict(r) for r in tier2_rows], indent=2, default=str))

    primary = [r for r in rows if r.output_dir_name == "decoding" and r.cost_scenario == "xau_conservative_45p"]
    primary_sorted = sorted(primary, key=lambda r: r.daily_sharpe, reverse=True)

    lines = [
        "# Derived Gold Strategy Backtest",
        "",
        "Data: 2026-05-03",
        "",
        "Escopo: backtest economico das regras Gold absorvidas como estrategias derivadas. Isto nao prova reverse engineering do EA original, porque 5R-1/M1 ja falhou em fidelidade operacional.",
        "",
        "Citação metodologica: custos e turnover dominam sistemas curtos `[systematic_trading, p.182-197]`; regras mineradas exigem inferencia anti-overfit via DSR/bootstrap antes de qualquer leitura substantiva `[advances_fin_ml, p.196-211]`.",
        "",
        "## Guardrails",
        "",
        "| Item | Estado |",
        "|---|---|",
        "| Reverse engineering confirmado | `false` |",
        "| Decisao de estrategia permitida | `false` |",
        "| Capital | 100% Plano C |",
        "| Plano A | DORMANT |",
        "| Frozen rules alteradas | `false` |",
        "| Tipo do teste | `derived_strategy_backtest` |",
        "",
        "## Cost Model",
        "",
        "XAUUSD usa pip_size=0.01 no replicator. Cenários round-trip:",
        "",
        "| Scenario | Cost pips/trade | Interpretação |",
        "|---|---:|---|",
        "| gross_0p | 0 | bruto, apenas diagnostico |",
        "| xau_conservative_45p | 45 | ~0.45 USD/oz RT, conservador para spread/slippage simples |",
        "| xau_stress_80p | 80 | stress de custo para turnover alto |",
        "",
        "## Resultado Principal — M5, custo conservador 45p",
        "",
        "| system | family | fidelity | n | period | trades/yr | total net pips | avg/trade | win% | PF | Sharpe | boot_lo | OOS Sharpe | OOS boot_lo | WF+ | maxDD pips |",
        "|---|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in primary_sorted:
        lines.append(
            f"| {r.system_id} | {r.family} | {_fmt(r.fidelity_score,4)} | {r.n_trades} | {r.start}..{r.end} | "
            f"{_fmt(r.trades_per_year,1)} | {_fmt(r.total_net_pips,1)} | {_fmt(r.avg_net_pips,2)} | "
            f"{_fmt(100*r.win_rate,1)} | {_fmt(r.profit_factor,2)} | {_fmt(r.daily_sharpe,3)} | "
            f"{_fmt(r.boot_lo,3)} | {_fmt(r.oos_sharpe,3)} | {_fmt(r.oos_boot_lo,3)} | "
            f"{r.wf_positive}/{r.wf_total} | {_fmt(r.max_drawdown_pips,1)} |"
        )

    lines.extend([
        "",
        "## Sensibilidade Por Custo",
        "",
        "Tabela mostra Sharpe diario anualizado por output e cenário. `decoding` = M5; `decoding_m1` = M1 quando existente.",
        "",
        "| system | output | gross Sharpe | 45p Sharpe | 80p Sharpe | 45p total pips | 45p OOS boot_lo |",
        "|---|---|---:|---:|---:|---:|---:|",
    ])
    for sid in GOLD_SYSTEMS:
        for od in ["decoding", "decoding_m1"]:
            subset = [r for r in rows if r.system_id == sid and r.output_dir_name == od]
            if not subset:
                continue
            by = {r.cost_scenario: r for r in subset}
            r45 = by.get("xau_conservative_45p")
            lines.append(
                f"| {sid} | {od} | {_fmt(by.get('gross_0p').daily_sharpe if by.get('gross_0p') else None)} | "
                f"{_fmt(r45.daily_sharpe if r45 else None)} | {_fmt(by.get('xau_stress_80p').daily_sharpe if by.get('xau_stress_80p') else None)} | "
                f"{_fmt(r45.total_net_pips if r45 else None,1)} | {_fmt(r45.oos_boot_lo if r45 else None)} |"
            )

    any_boot_pass = any(r.pass_full_bootstrap and r.pass_oos_bootstrap for r in primary)
    lines.extend([
        "",
        "## Leitura",
        "",
        f"- Systems Gold testados no M5 principal: {len(primary)}.",
        f"- Algum M5+45p passou simultaneamente bootstrap full e OOS? {'sim' if any_boot_pass else 'nao'}.",
        "- Mesmo se algum Sharpe bruto parecer positivo, fidelity_score <0.60 impede alegar que isto replica o EA original.",
        "- Resultado positivo aqui seria apenas hipotese derivada; sem bootstrap/OOS positivo, nao ha robustez suficiente nem para essa leitura derivada.",
        "",
        "## Caveats metodologicos",
        "",
        "Os gates `pass_basic_positive / pass_full_bootstrap / pass_oos_bootstrap` deste script **nao sao** os gates §2.4 do mandate (PBO, DSR p<0.05, WF≥6/8 com CPCV purgado, OOS bootstrap CI 99.9%, cross-lib ±3pp). Diferencas relevantes:",
        "",
        "- **Walk-forward**: 8 splits contiguos do indice diario, sem purge nem embargo. Mandate usa CPCV purgado `[advances_fin_ml, p.196-211]`. Esta WF e mais frouxa.",
        "- **PBO ausente**: o script nao computa Probability of Backtest Overfitting. Mandate exige PBO<0.5.",
        "- **DSR**: reportado em `dsr_p` mas nao usado como pass/fail. A formula de variancia segue Bailey/Lopez de Prado com kurtose excess (correcao 2026-05-03).",
        "- **Bootstrap CI 99.9%** e severo por construcao: regras com Sharpe<~0.5 e span<2y dificilmente passam, mesmo com sinal real. `boot_lo > 0` aqui nao e equivalente a `mandate-PASS`.",
        "- **Custo over-amortizado**: o replicator dispara muito mais que o EA real (count_ratio 10-35x em varios systems). 45p × 7000 trades/yr penaliza a regra disparada indiscriminadamente. Nao testa 'a logica subjacente filtrada para casar a frequencia real' — testa a regra em modo over-fire. Resposta negativa aqui nao implica logica subjacente sem edge.",
        "- **OOS = ultimos 20% dos dias com atividade**, nao calendar 20%. Para systems com span curto, OOS pode ter ~50-100 dias e bootstrap OOS e ruidoso.",
        "",
        "Conclusao: este teste e diagnostico de derived_strategy_backtest. Pass/fail aqui nao autoriza nem bloqueia Stage 3 — Stage 3 proper aplica os gates §2.4.",
        "",
        "## Tier 2 Forense — Frequency-Capped k=n_real",
        "",
        "Objetivo: responder se o resultado negativo foi causado apenas por over-fire. Este teste reduz cada synthetic stream para `k = n_real_trades` sem mexer em `frozen_rules/`.",
        "",
        "Seletores:",
        "",
        "- `uniform_time_k_n_real`: seleciona k trades uniformemente ao longo do tempo. Nao usa PnL futuro nem features; e o unico seletor minimamente honesto.",
        "- `oracle_best_net_pips_k_n_real_nontradeable`: seleciona ex-post os melhores trades por net_pips. Isto e um upper bound nao-tradeavel, usado apenas para medir se existia sinal dentro do over-fire.",
        "- `random_p95`: percentil 95 de 500 subsamples aleatorios de mesmo k/turnover, para saber se o seletor uniforme bate acaso.",
        "",
        "Cenario abaixo: M5 `decoding`, custo XAU conservador 45p.",
        "",
        "| system | mode | n_orig | k | total pips | Sharpe | boot_lo | OOS Sharpe | OOS boot_lo | WF+ | random Sharpe p95 | random total pips p95 |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ])
    tier2_primary = [
        r for r in tier2_rows
        if r.output_dir_name == "decoding" and r.cost_scenario == "xau_conservative_45p"
    ]
    for r in sorted(tier2_primary, key=lambda x: (x.selection_mode, x.daily_sharpe), reverse=True):
        lines.append(
            f"| {r.system_id} | {r.selection_mode} | {r.n_synthetic_original} | {r.n_selected} | "
            f"{_fmt(r.total_net_pips,1)} | {_fmt(r.daily_sharpe)} | {_fmt(r.boot_lo)} | "
            f"{_fmt(r.oos_sharpe)} | {_fmt(r.oos_boot_lo)} | {r.wf_positive}/{r.wf_total} | "
            f"{_fmt(r.random_sharpe_p95)} | {_fmt(r.random_total_pips_p95,1)} |"
        )

    uniform = [r for r in tier2_primary if r.selection_mode == "uniform_time_k_n_real"]
    oracle = [r for r in tier2_primary if r.selection_mode == "oracle_best_net_pips_k_n_real_nontradeable"]
    uniform_boot_pass = any(not math.isnan(r.boot_lo) and r.boot_lo > 0 and not math.isnan(r.oos_boot_lo) and r.oos_boot_lo > 0 for r in uniform)
    oracle_boot_pass = any(not math.isnan(r.boot_lo) and r.boot_lo > 0 and not math.isnan(r.oos_boot_lo) and r.oos_boot_lo > 0 for r in oracle)
    lines.extend([
        "",
        "Leitura Tier 2:",
        "",
        f"- Algum seletor uniforme passou bootstrap full e OOS? {'sim' if uniform_boot_pass else 'nao'}.",
        f"- Algum oracle ex-post passou bootstrap full e OOS? {'sim' if oracle_boot_pass else 'nao'}.",
        "- Se o uniforme falha, nao ha evidencia tradeavel de que apenas reduzir frequencia salve a regra.",
        "- Se o oracle passa, isso so prova que havia bons trades ex-post dentro do over-fire; nao fornece regra executavel.",
        "",
        "## Arquivos",
        "",
        f"- JSON parseable: `{out_json.relative_to(base)}`",
        f"- Tier 2 JSON parseable: `{out_tier2_json.relative_to(base)}`",
        f"- Relatorio: `{out_md.relative_to(base)}`",
        "",
    ])
    out_md.write_text("\n".join(lines))


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--systems", nargs="*", default=GOLD_SYSTEMS)
    ap.add_argument("--output-dirs", nargs="*", default=["decoding", "decoding_m1"])
    ap.add_argument("--report-name", default="DERIVED_GOLD_BACKTEST.md")
    ap.add_argument("--json-name", default="derived_gold_backtest.json")
    ap.add_argument("--tier2-json-name", default="derived_gold_backtest_tier2.json")
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    base = Path(__file__).resolve().parent.parent
    rows: list[BacktestStats] = []
    tier2_rows: list[Tier2Stats] = []
    for sid in args.systems:
        for output_dir_name in args.output_dirs:
            for scenario, cost_pips in COST_SCENARIOS.items():
                stats = compute_stats(base, sid, output_dir_name, scenario, cost_pips)
                if stats is not None:
                    rows.append(stats)
                tier2_rows.extend(compute_tier2_stats(base, sid, output_dir_name, scenario, cost_pips))
    if not rows:
        print("No synthetic trades found for requested systems/output dirs", file=sys.stderr)
        return 1
    diag = base / "_diagnostics"
    diag.mkdir(parents=True, exist_ok=True)
    out_md = diag / args.report_name
    out_json = diag / args.json_name
    out_tier2_json = diag / args.tier2_json_name
    write_report(base, rows, tier2_rows, out_md, out_json, out_tier2_json)
    print(f"Wrote {out_md}")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_tier2_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
