"""Reporting helpers for the weekly momentum study.

The report is deterministic Markdown generated by Python. LLM interpretation is
kept outside runtime per repository convention; the generated report includes a
manual/AI review placeholder instead.

Metric citations: Sharpe/Sortino/Calmar are standard performance diagnostics as
summarized in `[trading_systems_methods, ch.21]` and downside-deviation Sortino
is tracked in this repo with `[advances_fin_ml, p.275]`.
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from market_lab.backtest.metrics.performance import sortino
from market_lab.backtest.metrics.standard_report import load_spy_series
from studies.weekly_momentum.core import WeeklyMomentumConfig, WeeklyMomentumResult


def config_slug(config: WeeklyMomentumConfig) -> str:
    """Stable folder slug for one weekly momentum config."""
    neg = "neg1" if config.allow_negative_momentum else "neg0"
    defensive = f"def{config.defensive_asset.lower()}" if config.defensive_asset else "defcash"
    market_filter = (
        f"mf{config.market_filter_type}{config.market_filter_days}"
        if config.market_filter_type != "none"
        else "mf0"
    )
    return (
        f"lb{config.lookback_days}_sig{config.signal_weekday}"
        f"_sell{config.sell_delay_days}_sd{config.settlement_delay_days}_k{config.top_k}"
        f"_{neg}_{defensive}_{market_filter}"
    )


def build_spy_benchmark(
    strategy_equity: pd.Series,
    initial_cash: float,
    spy_path: str | Path = "data/tiingo/daily/prices/SPY.parquet",
) -> tuple[pd.Series, pd.Series]:
    """Load and align SPY buy-and-hold equity/returns to the strategy window."""
    spy = load_spy_series(spy_path)
    start = pd.Timestamp(strategy_equity.index.min())
    end = pd.Timestamp(strategy_equity.index.max())
    spy = spy.loc[(spy.index >= start) & (spy.index <= end)].dropna()
    if len(spy) < 2:
        raise ValueError(f"SPY benchmark has insufficient data in {start.date()}..{end.date()}")
    spy_equity = (spy / float(spy.iloc[0]) * initial_cash).rename("spy_equity")
    spy_returns = spy_equity.pct_change(fill_method=None).fillna(0.0).rename("spy_return")
    return spy_equity, spy_returns


def compute_report_metrics(equity: pd.Series, returns: pd.Series) -> dict[str, float]:
    """Compute report metrics for one equity/returns series."""
    returns = returns.dropna()
    equity = equity.dropna()
    if len(equity) < 2 or len(returns) < 2:
        return {key: float("nan") for key in _METRIC_ORDER}

    total_return = float(equity.iloc[-1] / equity.iloc[0] - 1.0)
    years = len(returns) / 252.0
    cagr = (float(equity.iloc[-1] / equity.iloc[0]) ** (1.0 / years) - 1.0) if years > 0 else np.nan
    dd = equity / equity.cummax() - 1.0
    std = float(returns.std(ddof=1))
    sharpe = float(returns.mean() / std * np.sqrt(252.0)) if std > 0 else 0.0
    mdd = float(dd.min())
    return {
        "total_return": total_return,
        "cagr": float(cagr),
        "mdd": mdd,
        "sharpe": sharpe,
        "sortino": float(sortino(returns, periods_per_year=252)),
        "calmar": float(cagr / abs(mdd)) if mdd < 0 else float("inf"),
        "vol_annual": float(std * np.sqrt(252.0)),
        "skew": float(returns.skew()),
        "kurt": float(returns.kurtosis()),
        "var_5": float(max(-returns.quantile(0.05), 0.0)),
        "best_day": float(returns.max()),
        "worst_day": float(returns.min()),
    }


def write_run_outputs(
    out_dir: Path,
    variation: str,
    config: WeeklyMomentumConfig,
    result: WeeklyMomentumResult,
    n_assets: int,
    universe_label: str,
    spy_path: str | Path = "data/tiingo/daily/prices/SPY.parquet",
) -> dict[str, Any]:
    """Write CSV/JSON/plots/report for one run and return summary metadata."""
    out_dir.mkdir(parents=True, exist_ok=True)
    plots_dir = out_dir / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)

    spy_equity, spy_returns = build_spy_benchmark(
        result.equity,
        initial_cash=config.initial_cash,
        spy_path=spy_path,
    )
    aligned = _align_strategy_and_spy(result.equity, result.returns, spy_equity, spy_returns)
    strategy_equity = aligned["strategy_equity"]
    strategy_returns = aligned["strategy_return"]
    spy_equity = aligned["spy_equity"]
    spy_returns = aligned["spy_return"]

    result.equity.to_csv(out_dir / "equity.csv")
    result.returns.to_csv(out_dir / "returns.csv")
    result.weights.to_csv(out_dir / "weights.csv")
    result.trades.to_csv(out_dir / "trades.csv", index=False)
    pd.DataFrame({"spy_equity": spy_equity, "spy_return": spy_returns}).to_csv(
        out_dir / "benchmark_spy.csv"
    )

    strategy_metrics = compute_report_metrics(strategy_equity, strategy_returns)
    spy_metrics = compute_report_metrics(spy_equity, spy_returns)
    metrics_df = pd.DataFrame({"strategy": strategy_metrics, "spy": spy_metrics})
    metrics_df.to_csv(out_dir / "metrics.csv")

    payload = {
        "variation": variation,
        "universe_label": universe_label,
        "config_slug": config_slug(config),
        "config": asdict(config),
        "n_assets": int(n_assets),
        "date_start": str(strategy_equity.index.min().date()),
        "date_end": str(strategy_equity.index.max().date()),
        "metrics": {
            "strategy": _jsonify_metrics(strategy_metrics),
            "spy": _jsonify_metrics(spy_metrics),
        },
        "n_trades": int(len(result.trades)),
        "n_buys": int((result.trades["action"] == "buy").sum()) if not result.trades.empty else 0,
        "n_sells": int((result.trades["action"] == "sell").sum()) if not result.trades.empty else 0,
    }
    (out_dir / "config.json").write_text(json.dumps(asdict(config), indent=2) + "\n")
    (out_dir / "metrics.json").write_text(json.dumps(payload, indent=2) + "\n")

    plot_paths = {
        "equity": plots_dir / "equity_vs_spy.png",
        "drawdown": plots_dir / "drawdown_vs_spy.png",
        "relative": plots_dir / "relative_to_spy.png",
        "rolling_sharpe": plots_dir / "rolling_252d_sharpe.png",
        "rolling_windows": plots_dir / "rolling_windows_1_3_5_10y.png",
    }
    plot_equity_vs_spy(strategy_equity, spy_equity, plot_paths["equity"], variation, config)
    plot_drawdown_vs_spy(strategy_equity, spy_equity, plot_paths["drawdown"], variation, config)
    plot_relative_to_spy(strategy_equity, spy_equity, plot_paths["relative"], variation, config)
    plot_rolling_sharpe(strategy_equity, spy_equity, plot_paths["rolling_sharpe"], variation, config)
    plot_rolling_window_relative_returns(
        strategy_equity,
        spy_equity,
        plot_paths["rolling_windows"],
        variation,
        config,
    )

    write_report(out_dir / "report.md", variation, config, payload, result.trades, plot_paths)
    return payload


def plot_equity_vs_spy(
    strategy_equity: pd.Series,
    spy_equity: pd.Series,
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
) -> None:
    fig, ax = plt.subplots(figsize=(11, 7))
    ax.plot(strategy_equity.index, strategy_equity.values, label="Weekly momentum", linewidth=1.5)
    ax.plot(spy_equity.index, spy_equity.values, label="SPY buy & hold", color="black", linestyle="--", linewidth=1.5)
    ax.set_yscale("log")
    ax.set_title(f"Weekly momentum {variation} vs SPY - {config_slug(config)}")
    ax.set_ylabel("Equity ($, log scale)")
    ax.grid(True, which="both", alpha=0.35)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)


def plot_drawdown_vs_spy(
    strategy_equity: pd.Series,
    spy_equity: pd.Series,
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
) -> None:
    fig, ax = plt.subplots(figsize=(11, 7))
    for label, equity, color, linestyle in [
        ("Weekly momentum", strategy_equity, "#0066ff", "-"),
        ("SPY buy & hold", spy_equity, "black", "--"),
    ]:
        dd = equity / equity.cummax() - 1.0
        ax.plot(dd.index, dd.values * 100.0, label=label, color=color, linestyle=linestyle, linewidth=1.4)
    ax.set_title(f"Drawdown vs SPY - {variation} - {config_slug(config)}")
    ax.set_ylabel("Drawdown (%)")
    ax.grid(True, alpha=0.35)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)


def plot_relative_to_spy(
    strategy_equity: pd.Series,
    spy_equity: pd.Series,
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
) -> None:
    ratio = (strategy_equity / strategy_equity.iloc[0]) / (spy_equity / spy_equity.iloc[0])
    fig, ax = plt.subplots(figsize=(11, 7))
    ax.plot(ratio.index, ratio.values, label="Strategy / SPY", linewidth=1.5)
    ax.axhline(1.0, color="black", linestyle="--", linewidth=1.0)
    ax.set_yscale("log")
    ax.set_title(f"Relative equity to SPY - {variation} - {config_slug(config)}")
    ax.set_ylabel("Strategy equity / SPY equity")
    ax.grid(True, which="both", alpha=0.35)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)


def plot_rolling_sharpe(
    strategy_equity: pd.Series,
    spy_equity: pd.Series,
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
    window_days: int = 252,
) -> None:
    fig, ax = plt.subplots(figsize=(11, 7))
    for label, equity, color, linestyle in [
        ("Weekly momentum", strategy_equity, "#0066ff", "-"),
        ("SPY buy & hold", spy_equity, "black", "--"),
    ]:
        returns = equity.pct_change(fill_method=None).dropna()
        rolling = returns.rolling(window_days).mean() / returns.rolling(window_days).std(ddof=1)
        rolling = rolling * np.sqrt(252.0)
        ax.plot(rolling.index, rolling.values, label=label, color=color, linestyle=linestyle, linewidth=1.3)
    ax.axhline(0.0, color="black", linewidth=0.8, alpha=0.5)
    ax.set_title(f"Rolling 252d Sharpe - {variation} - {config_slug(config)}")
    ax.set_ylabel("Sharpe")
    ax.grid(True, alpha=0.35)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)


def plot_rolling_window_relative_returns(
    strategy_equity: pd.Series,
    spy_equity: pd.Series,
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
    windows_years: tuple[int, ...] = (1, 3, 5, 10),
) -> None:
    """Plot rolling CAGR for strategy vs SPY over 1/3/5/10y windows.

    Rolling-window comparison is a regime-stability diagnostic; it helps avoid
    relying on one full-period CAGR and follows robustness-testing practice in
    `[trading_systems_methods, ch.21]`.
    """
    aligned = pd.concat({"strategy": strategy_equity, "spy": spy_equity}, axis=1).dropna()
    fig, axes = plt.subplots(2, 2, figsize=(14, 10), sharex=False)
    axes_flat = axes.ravel()
    for ax, years in zip(axes_flat, windows_years, strict=True):
        window_days = years * 252
        if len(aligned) <= window_days:
            ax.text(0.5, 0.5, f"Insufficient data for {years}y window", ha="center", va="center")
            ax.set_title(f"{years}y rolling CAGR")
            ax.grid(True, alpha=0.25)
            continue
        strat_cagr = (aligned["strategy"] / aligned["strategy"].shift(window_days)) ** (1.0 / years) - 1.0
        spy_cagr = (aligned["spy"] / aligned["spy"].shift(window_days)) ** (1.0 / years) - 1.0
        edge = strat_cagr - spy_cagr
        ax.plot(strat_cagr.index, strat_cagr.values * 100.0, label="Strategy", color="#0066ff", linewidth=1.2)
        ax.plot(spy_cagr.index, spy_cagr.values * 100.0, label="SPY", color="black", linestyle="--", linewidth=1.2)
        ax.fill_between(
            edge.index,
            0,
            edge.values * 100.0,
            where=edge.values >= 0,
            color="#16a34a",
            alpha=0.18,
            label="Strategy CAGR edge" if years == windows_years[0] else None,
        )
        ax.fill_between(edge.index, 0, edge.values * 100.0, where=edge.values < 0, color="#d62728", alpha=0.16)
        ax.axhline(0.0, color="black", linewidth=0.7, alpha=0.5)
        ax.set_title(f"{years}y rolling CAGR")
        ax.set_ylabel("CAGR (%)")
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8)
    fig.suptitle(f"Rolling window CAGR vs SPY - {variation} - {config_slug(config)}", y=0.995)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)


def write_report(
    out_path: Path,
    variation: str,
    config: WeeklyMomentumConfig,
    payload: dict[str, Any],
    trades: pd.DataFrame,
    plot_paths: dict[str, Path],
) -> None:
    """Write deterministic structured Markdown report."""
    strategy = payload["metrics"]["strategy"]
    spy = payload["metrics"]["spy"]
    rel_terminal = (1.0 + strategy["total_return"]) / (1.0 + spy["total_return"])
    recent_trades = trades.tail(10).copy() if not trades.empty else pd.DataFrame(columns=["date", "action", "symbols"])
    if not recent_trades.empty:
        recent_trades["date"] = recent_trades["date"].astype(str)

    lines = [
        f"# Weekly Momentum Report - {variation} / {config_slug(config)}",
        "",
        "## Strategy",
        "",
        f"- Universe variation: `{variation}` / `{payload['universe_label']}` using cached Tiingo tickers.",
        f"- Signal: rank by adjusted-close return over `{config.lookback_days}` trading bars `[stocks_on_the_move, p.60]`.",
        f"- Timing: signal weekday `{config.signal_weekday}`, sell after `{config.sell_delay_days}` trading bar(s), buy after settlement delay `{config.settlement_delay_days}`.",
        f"- Holdings: equal-weight top `{config.top_k}`; unchanged winners are held without churn.",
        f"- Allow negative momentum: `{config.allow_negative_momentum}`; defensive target: `{config.defensive_asset or 'cash'}`.",
        f"- Market regime filter: `{config.market_filter_symbol} > {config.market_filter_type.upper()}{config.market_filter_days}`" if config.market_filter_type != "none" else "- Market regime filter: disabled.",
        "- Benchmark: SPY buy & hold aligned to the strategy date range.",
        "",
        "## Result Summary",
        "",
        f"- Date range: `{payload['date_start']}` to `{payload['date_end']}`.",
        f"- Assets loaded: `{payload['n_assets']}`.",
        f"- Strategy CAGR: `{_fmt_pct(strategy['cagr'])}` vs SPY `{_fmt_pct(spy['cagr'])}`.",
        f"- Strategy MDD: `{_fmt_pct(strategy['mdd'])}` vs SPY `{_fmt_pct(spy['mdd'])}`.",
        f"- Strategy Sharpe: `{strategy['sharpe']:.3f}` vs SPY `{spy['sharpe']:.3f}`.",
        f"- Terminal relative wealth vs SPY: `{rel_terminal:.2f}x`.",
        "",
        "## Metrics",
        "",
        "| metric | strategy | SPY |",
        "|---|---:|---:|",
    ]
    for metric in _METRIC_ORDER:
        lines.append(
            f"| {metric} | {_fmt_metric(metric, strategy[metric])} | {_fmt_metric(metric, spy[metric])} |"
        )

    lines.extend([
        "",
        "## Plots",
        "",
        f"![Equity vs SPY]({_rel(out_path, plot_paths['equity'])})",
        "",
        f"![Drawdown vs SPY]({_rel(out_path, plot_paths['drawdown'])})",
        "",
        f"![Relative to SPY]({_rel(out_path, plot_paths['relative'])})",
        "",
        f"![Rolling Sharpe]({_rel(out_path, plot_paths['rolling_sharpe'])})",
        "",
        f"![Rolling Windows 1/3/5/10y]({_rel(out_path, plot_paths['rolling_windows'])})",
        "",
        "## Trades",
        "",
        f"- Total trade events: `{payload['n_trades']}` (`{payload['n_buys']}` buys, `{payload['n_sells']}` sells).",
        "",
    ])
    if recent_trades.empty:
        lines.append("No trades generated.")
    else:
        lines.append(recent_trades.to_markdown(index=False))

    lines.extend([
        "",
        "## Caveats",
        "",
        "- Current Tiingo cache universe implies survivorship bias until replaced by a point-in-time universe.",
        "- Daily close-to-close simulation is a research proxy, not an execution-grade intraday model.",
        "- Costs, taxes, slippage, borrow constraints and order liquidity are not modeled yet.",
        "- Top-1 stock momentum can produce extreme single-name path risk; inspect drawdown before promoting any lead.",
        "",
        "## Review Notes",
        "",
        "Deterministic report generated by the script. Add manual/AI interpretation here after reviewing plots and caveats.",
        "",
    ])
    out_path.write_text("\n".join(lines), encoding="utf-8")


_METRIC_ORDER = [
    "total_return",
    "cagr",
    "mdd",
    "sharpe",
    "sortino",
    "calmar",
    "vol_annual",
    "skew",
    "kurt",
    "var_5",
    "best_day",
    "worst_day",
]


def _align_strategy_and_spy(
    strategy_equity: pd.Series,
    strategy_returns: pd.Series,
    spy_equity: pd.Series,
    spy_returns: pd.Series,
) -> pd.DataFrame:
    return pd.concat(
        {
            "strategy_equity": strategy_equity,
            "strategy_return": strategy_returns,
            "spy_equity": spy_equity,
            "spy_return": spy_returns,
        },
        axis=1,
        sort=True,
    ).dropna()


def _fmt_pct(value: float) -> str:
    return f"{value * 100:.2f}%" if np.isfinite(value) else str(value)


def _fmt_metric(metric: str, value: float) -> str:
    if isinstance(value, str):
        return value
    if metric in {"total_return", "cagr", "mdd", "vol_annual", "var_5", "best_day", "worst_day"}:
        return _fmt_pct(value)
    if np.isposinf(value):
        return "+inf"
    if np.isneginf(value):
        return "-inf"
    return f"{value:.3f}" if np.isfinite(value) else "nan"


def _jsonify_metrics(metrics: dict[str, float]) -> dict[str, float | str]:
    out: dict[str, float | str] = {}
    for key, value in metrics.items():
        if np.isposinf(value):
            out[key] = "Infinity"
        elif np.isneginf(value):
            out[key] = "-Infinity"
        elif np.isnan(value):
            out[key] = "NaN"
        else:
            out[key] = float(value)
    return out


def _rel(report_path: Path, target: Path) -> str:
    return target.relative_to(report_path.parent).as_posix()
